title: "User Test 2025-MM-DD"
labels: ["User Test"]
body:
  - type: markdown
    attributes:
      value: |
        # User Test Notes
  
  - type: input
    id: location
    attributes:
      label: location
      value: "Office"
    validations:
      required: true

  - type: input
    id: hardware
    attributes:
      label: Hardware version
      value: "SP01"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Software version
      value: "v1.0.0"
    validations:
      required: true
  
  - type: textarea
    id: users
    attributes:
      label: Users
      placeholder: "Lt. Dan, Forrest Gump"
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Testing Goals
      value: |
        1.
        2.
        3.
        ...

  - type: textarea
    id: feedback
    attributes:
      label: Participant Observations & Feedback
      value: |
        - Task Completion Success Rate: [Completed / Partially Completed / Failed]
        - Errors Encountered: [Describe issues faced]
        - Confusing Elements: [List UI/UX elements that caused difficulty]
        - User Quotes ["Direct quotes from users"]
        - Suggested Improvements: [User’s perspective on improvements]

  - type: textarea
    id: behavioral
    attributes:
      label: Behavioral & Performance Metrics
      value: |
        - Time Taken per Task: [Record task completion times]
        - Navigation Efficiency: [Easy / Somewhat Difficult / Hard]
        - Unexpected Behaviors Noted: [Any unusual actions taken by the user]
        - Software Crashes or Bugs: [Yes/No + Description]

  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_
