title: "User Test 2025-MM-DD"
labels: ["User Test"]
body:
  - type: markdown
    attributes:
      value: |
        # User Test Notes
  
  - type: input
    id: location
    attributes:
      label: "# Location"
      value: "5855 Green Valley Cir #101"
    validations:
      required: true

  - type: input
    id: hardware
    attributes:
      label: Hardware version
      value: "SP01"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Software version
      placeholder: commit hash
    validations:
      required: true
  
  - type: input
    id: users
    attributes:
      label: Users
      placeholder: "Lt. Dan, Forrest Gump"
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Testing Goals
      placeholder: What are you testing?

  - type: textarea
    id: feedback
    attributes:
      label: Participant Observations & Feedback
      value: |
        Task Completion Success Rate
        
        Errors Encountered
        
        Confusing Elements
        
        User Suggestions / Quotes

  - type: textarea
    id: behavioral
    attributes:
      label: Behavioral & Performance Metrics
      value: |
        Time Taken per Task
        
        Navigation Efficiency
        
        Unexpected Behaviors Noted
        
        Software Crashes or Bugs

  - type: textarea
    id: risk
    attributes:
      label: Risk Assessment
      placeholder: Any new risks identified

  - type: markdown
    attributes:
      value: Fields can be edited after issue is created.
